name: flutter_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.0.9
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  intl: ^0.19.0
  get: ^4.6.6
  firebase_auth: ^4.17.8
  google_sign_in: ^6.1.5
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pic_login.png
