// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsXzsXUTYKa8oO8tccBtnOHeU6gaOmSbA',
    appId: '1:322422090371:web:a94a0fff6c9e331f82c9b6',
    messagingSenderId: '322422090371',
    projectId: 'dailoz-firebase',
    authDomain: 'dailoz-firebase.firebaseapp.com',
    storageBucket: 'dailoz-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPQHWKLMORwJpLFml7xxUUQVgo1vRxls',
    appId: '1:322422090371:android:94685cad819e176982c9b6',
    messagingSenderId: '322422090371',
    projectId: 'dailoz-firebase',
    storageBucket: 'dailoz-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX9zxTedHEHZEljbog6ULfNwgxsibrYNo',
    appId: '1:322422090371:ios:1a97609f1ec8353a82c9b6',
    messagingSenderId: '322422090371',
    projectId: 'dailoz-firebase',
    storageBucket: 'dailoz-firebase.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsXzsXUTYKa8oO8tccBtnOHeU6gaOmSbA',
    appId: '1:322422090371:web:b97e49ec047000e582c9b6',
    messagingSenderId: '322422090371',
    projectId: 'dailoz-firebase',
    authDomain: 'dailoz-firebase.firebaseapp.com',
    storageBucket: 'dailoz-firebase.appspot.com',
  );
}
